### ISSUE TITLE
Some question about use in Py3.5

### ISSUE THREAD

**Issue by MKFMIKU** [leelabcnbc/cnnvis-pytorch#1]
The repo is awesome and useful, but when I try to use it in my own project wrote in py3.5, which get some errors like below:

```
----> 3 from enum import Enum, auto
      4 from functools import partial
      5 

ImportError: cannot import name 'auto'
```

The auto is unique in py3.6 and don't contain in py3.5, how can I change the code to let it work?

Looking for your help

**Comment by zym1010** [comment]
I believe auto is only used to define layer type enumeration in an elegant way. You can try replacing those lines using auto with some concrete numbers, 0,1,2,etc.

Yimeng Zhang
